INSERT INTO book (title, deploy_date, copy_number) VALUES ('The Da Vinci Code', '2003-04-01', 10);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Deathly Hallows', '2007-07-14', 5);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Philosopher''s Stone', '1997-06-26', 6);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Order of the Phoenix', '2003-06-27', 11);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Fifty Shades of Grey', '2011-06-20', 7);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Goblet of Fire', '2000-07-08', 7);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Chamber of Secrets', '1998-07-02', 1);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Prisoner of Azkaban', '1999-07-08', 5);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Angels and Demons', '2000-05-01', 7);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Harry Potter and the Half-blood Prince:Children''s Edition', '2005-07-16', 4);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Fifty Shades Darker', '2012-04-17', 11);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Twilight', '2005-10-5', 8);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Girl with the Dragon Tattoo', '2005-08-01', 3);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Fifty Shades Freed', '2012-04-17', 45);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('The Lost Symbol', '2009-09-15', 34);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('New Moon', '2006-08-21', 1);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Deception Point', '2001-01-01', 4);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('Eclipse', '2007-08-07', 6);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('The Lovely Bones', '2002-01-01', 8);
INSERT INTO book (title, deploy_date, copy_number) VALUES ('The Curious Incident of the Dog in the Night-time', '2003-05-01', 11);